---

- hosts: master_node
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: "my-cluster"
      cluster.initial_master_nodes: "master_node"
      discovery.seed_hosts: "192.168.58.60"
      network.host: [_local_,_eth1_]
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment

- hosts: data_node_1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "my-cluster"
      cluster.initial_master_nodes: "master_node"
      discovery.seed_hosts: "192.168.58.60"
      network.host: [_local_,_eth1_]
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment

- hosts: data_node_2
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      cluster.name: "my-cluster"
      cluster.initial_master_nodes: "master_node"
      discovery.seed_hosts: "192.168.58.60"
      network.host: [_local_,_eth1_]
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment

- name: Install Kibana
  hosts: kibana
  tags: kibana
  tasks:
    - import_role:
        name: kibana