all:
  vars:
    ansible_connection: ssh
    ansible_user: vagrant
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

elastic-search:
  hosts:
    master_node:
      ansible_host: 192.168.58.60
    data_node_1:
      ansible_host: 192.168.58.61
    data_node_2:
      ansible_host: 192.168.58.62
kibana:
  hosts:
    192.168.58.60: